baseURL = "https://metahx.github.io/"
languageCode = "en-us"
title = "MetaHX"
theme = "xmin"
publishDir = "./docs"

disqusShortname = "metahx"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 4

